### ISSUE TITLE
Build fails when using react-native-x.

### ISSUE THREAD

**Issue by maotora** [yeyintkoko/react-native-send-sms#1]
Hi,

When i use your lib i get 

```
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-sms-x'.
   > failed to find Build Tools revision 24.0.1
```

I tried to check if everything was okay and it was as how you recommended in **README** (double checked).

I can't really figure out what's wrong but i thought i should let you know about this.

Thanks.

**Comment by yeyintkoko** [comment]
You just need to install android build tool revision 24.0.1.

![screenshot from 2016-11-17 08-30-37](https://cloud.githubusercontent.com/assets/10381355/20373532/d3e0701e-aca0-11e6-85ae-3d69d1fa3c57.png)

**Comment by maotora** [comment]
It does work!

Thank you very much!

I think you should add that in the **README** too.
