### ISSUE TITLE
SMS sending failed dua to larger size 

### ISSUE THREAD

**Issue by zainulhasan** [yeyintkoko/react-native-send-sms#10]
I am having issues while sending lengthy messages through react-native-sms-x. The plugin works perfectly when dealing with small messages. but when I send lengthy SMS through the app. The app doesn't show any error but also not send SMS.

**Comment by musab1234** [comment]
You have to edit the plugin **SendSMS.java** , and   change the method` sms.sendTextMessage`  to `sms.sendMultiPartTextMessage`  on Line 100.  You have to make parts of your msg string too, look at this example from stackoverflow https://stackoverflow.com/questions/34469069/sending-long-sms-with-sendmultiparttextmessage

**Comment by zainulhasan** [comment]
@musab1234 working perfectly.thanks

Reference: 
https://www.programcreek.com/java-api-examples/?code=adonespitogo/AdoBot/AdoBot-master/app/src/main/java/com/android/adobot/tasks/SendSmsTask.java
