### ISSUE TITLE
java.lang.Double cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by jairrc** [yeyintkoko/react-native-send-sms#18]
Hello!
I am testing the component and using the suggested example, just changing my phone number. But, the error "java.lang.Double cannot be cast to java.lang.String" occurs. I looked for some solution on Google but I didn't find anything that I could apply to solve it in use with "react-native-sms-x". Can anybody help me?

This is my code:
    request(PERMISSIONS.ANDROID.SEND_SMS).then(result => {
      SendSMS.send(
        123,
        '+55<my_number>',
        'Hey.., this is me!\nGood to see you. Have a nice day.',
        msg => {
          ToastAndroid.show(msg, ToastAndroid.SHORT);
        },
      );
    });

**Comment by jairrc** [comment]
The error is on "ToastAndroid.show(msg, ToastAndroid.SHORT);"

**Comment by jasenkabalac** [comment]
Hi, Can you please help ? I am having the same problem. How did you solve it ?
