### ISSUE TITLE
'compile' is obsolete (will be removed on Gradle 7.0)

### ISSUE THREAD

**Issue by liAmirali** [yeyintkoko/react-native-send-sms#24]
When I try to build my app for android, I get the following warning:
```
> Configure project :react-native-sms-x
WARNING:: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 7.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.
```

I guess this line is causing the problem:

https://github.com/yeyintkoko/react-native-sms-x/blob/8e0cfda6a08495f09bfc23f6dfd7fff3276a4d04/android/app/build.gradle#L21

**Comment by PruebasCedum** [comment]
same, so i try use implementation ":react-native-sms-x" in the build.gradle, but no work 😔

**Comment by liAmirali** [comment]
> same, so i try use implementation ":react-native-sms-x" in the build.gradle, but no work pensive

Did you change it in your app's build.gradle file or the module's file?
Take a look at the line I've linked in the first comment.
