### ISSUE TITLE
Error: Duplicate module name

### ISSUE THREAD

**Issue by guilhermedotcamargo** [yeyintkoko/react-native-send-sms#5]
Hi, after installed react-native-sms-x, when run _npm start_, this error returns

> root@developer1:/var/www/html/senderfy# npm start

> senderfy@0.1.0 start /var/www/html/senderfy
> react-native-scripts start

>14:43:30: Starting packager...
>***ERROR STARTING PACKAGER***
>Starting React Native packager...
>Scanning folders for symlinks in /var/www/html/senderfy/node_modules (15ms)
>Loading dependency graph.

>jest-haste-map: @providesModule naming collision:
>  Duplicate module name: react-native
>  Paths: /var/www/html/senderfy/node_modules/react-native-sms-x/node_modules/react->native/package.json collides with /var/www/html/senderfy/node_modules/react-native/package.json

>This warning is caused by a @providesModule declaration with the same name across two different files.

**Comment by jkevingutierrez** [comment]
Any solution to this?
