### ISSUE TITLE
undefined is not an object(evaluating '_reactNativeSmsX.default.send')

### ISSUE THREAD

**Issue by zainulhasan** [yeyintkoko/react-native-send-sms#9]
Hi everyone I get this error when I click sends SMS button.

```
sendSMSFunction() {
    SendSMS.send(123, "+95912345678", "Hey.., this is me!\nGood to see you. Have a nice day.",
      (msg)=>{
        ToastAndroid.show(msg, ToastAndroid.SHORT);
      }
    );
  }

```

i am using code from example.
Thanks
react-native-cli: 2.0.1
react-native: 0.57.3

![screenshot_20181024-143252_sms](https://user-images.githubusercontent.com/10378868/47421942-13fc3a80-d79b-11e8-9159-2eff688b63fe.jpg)

**Comment by zainulhasan** [comment]
problem is solved and application is working 💯. there was issues with app permissions.

**Comment by Riki220999** [comment]
can you share tutorial

**Comment by zainulhasan** [comment]
I was having this issue because I did not add `"import com.someone.sendsms.SendSMSPackage; 
"` in MainApplication.java and `<uses-permission android:name="android.permission.SEND_SMS" />` in AndroidManifest.xml.
